name: ServiceNow Operations

on:
  workflow_call:
    secrets: 
      hmac_token:
        required: true
    inputs:
      action:
        required: true
        type: string
      instance:
        required: true
        type: string
      body:
        required: false
        type: string
      cr_id:
        required: false
        type: string
      timeout_minutes:
        required: false
        type: number

jobs:
  create-cr:
    if: ${{ inputs.action == 'create' }}
    runs-on: ubuntu-latest
    outputs:
      cr_id: ${{ steps.run.outputs.cr_id }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          chmod +x ./scripts/servicenow.sh
          ./scripts/servicenow.sh \
            -a "${{ inputs.action }}" \
            -i "${{ inputs.instance }}" \
            -t "${{ secrets.hmac_token }}" \
            ${ inputs.body && format('-b \'{0}\'', inputs.body) || '' } \
            ${ inputs.cr_id && format('-c {0}', inputs.cr_id) || '' } \
            ${ inputs.timeout_minutes && format('-m {0}', inputs.timeout_minutes) || '' }