name: ServiceNow Operations

on:
  workflow_call:
    secrets: 
      hmac_token:
        required: true
    inputs:
      action:
        required: true
        type: string
      instance:
        required: true
        type: string

      body:
        required: false
        type: string
      cr_id:
        required: false
        type: string
      timeout_minutes:
        required: false
        type: number

jobs:
  create-cr:
    if: ${{ inputs.action == 'create' }}
    runs-on: ubuntu-latest
    outputs:
      cr_id: ${{ steps.run.outputs.cr_id }}
    steps:
      - uses: actions/checkout@v4
      - id: run
        run: |
          ./scripts/servicenow.sh \
            -a create \
            -i "${{ inputs.instance }}" \
            -t "${{ secrets.hmac_token }}" \
            -b '${{ inputs.body }}'

  wait-cr:
    if: ${{ inputs.action == 'wait' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          ./scripts/servicenow.sh \
            -a wait \
            -i "${{ inputs.instance }}" \
            -t "${{ secrets.hmac_token }}" \
            -c "${{ inputs.cr_id }}" \
            -m "${{ inputs.timeout_minutes || '' }}"

  close-cr:
    if: ${{ inputs.action == 'close' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          ./scripts/servicenow.sh \
            -a close \
            -i "${{ inputs.instance }}" \
            -t "${{ secrets.hmac_token }}" \
            -c "${{ inputs.cr_id }}"
